# -*- coding: utf-8 -*-
"""json to jsonL converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkixuFEA8GQOxBItv0uX3slC51kFFYzr
"""

import json

def json_to_jsonl(json_file_path, jsonl_file_path):
    """
    Converts a JSON file to a JSONL file.

    Args:
        json_file_path (str): The path to the input JSON file.
        jsonl_file_path (str): The path to the output JSONL file.
    """
    with open(json_file_path, 'r') as infile, open(jsonl_file_path, 'w') as outfile:
        data = json.load(infile)
        if isinstance(data, list):
            for item in data:
                outfile.write(json.dumps(item) + '\n')
        else:
            # If the JSON is not a list, treat it as a single object
            outfile.write(json.dumps(data) + '\n')

json_to_jsonl('tickets_completi.json', 'output.jsonl')

print("Conversion complete. 'output.jsonl' created.")